// Curated starter set. The optional FreeDict import supplies the large dictionary.
const RAW = `hello|привет
goodbye|до свидания
please|пожалуйста
thank you|спасибо
yes|да
no|нет
sorry|извините
welcome|добро пожаловать
friend|друг
family|семья
mother|мать
father|отец
child|ребёнок
woman|женщина
man|мужчина
person|человек
people|люди
name|имя
home|дом
room|комната
door|дверь
window|окно
table|стол
chair|стул
bed|кровать
book|книга
page|страница
pen|ручка
paper|бумага
bag|сумка
phone|телефон
computer|компьютер
screen|экран
key|ключ
light|свет
water|вода
food|еда
bread|хлеб
rice|рис
fruit|фрукт
apple|яблоко
banana|банан
vegetable|овощ
potato|картофель
tomato|помидор
milk|молоко
cheese|сыр
egg|яйцо
coffee|кофе
tea|чай
breakfast|завтрак
lunch|обед
dinner|ужин
day|день
night|ночь
morning|утро
evening|вечер
today|сегодня
tomorrow|завтра
yesterday|вчера
week|неделя
month|месяц
year|год
hour|час
minute|минута
time|время
moment|момент
early|рано
late|поздно
now|сейчас
soon|скоро
always|всегда
never|никогда
often|часто
sometimes|иногда
first|первый
last|последний
next|следующий
new|новый
old|старый
young|молодой
big|большой
small|маленький
long|длинный
short|короткий
good|хороший
bad|плохой
easy|лёгкий
difficult|трудный
simple|простой
important|важный
interesting|интересный
beautiful|красивый
happy|счастливый
sad|грустный
angry|сердитый
tired|уставший
ready|готовый
busy|занятый
free|свободный
strong|сильный
weak|слабый
fast|быстрый
slow|медленный
warm|тёплый
cold|холодный
hot|горячий
clean|чистый
dirty|грязный
safe|безопасный
quiet|тихий
loud|громкий
open|открытый
closed|закрытый
right|правильный
wrong|неправильный
different|другой
same|такой же
every|каждый
some|некоторые
many|много
few|мало
more|больше
less|меньше
all|все
none|ни один
here|здесь
there|там
inside|внутри
outside|снаружи
near|близко
far|далеко
above|выше
below|ниже
before|до
after|после
between|между
with|с
without|без
because|потому что
although|хотя
if|если
when|когда
where|где
why|почему
how|как
what|что
who|кто
which|который
city|город
village|деревня
street|улица
road|дорога
bridge|мост
station|станция
airport|аэропорт
train|поезд
bus|автобус
car|машина
bicycle|велосипед
ticket|билет
map|карта
place|место
country|страна
world|мир
river|река
lake|озеро
sea|море
mountain|гора
forest|лес
tree|дерево
flower|цветок
sky|небо
sun|солнце
moon|луна
star|звезда
rain|дождь
snow|снег
wind|ветер
weather|погода
spring|весна
summer|лето
autumn|осень
winter|зима
animal|животное
bird|птица
cat|кошка
dog|собака
fish|рыба
horse|лошадь
school|школа
university|университет
student|студент
teacher|учитель
lesson|урок
class|занятие
subject|предмет
language|язык
word|слово
sentence|предложение
text|текст
letter|буква
sound|звук
voice|голос
meaning|значение
translation|перевод
question|вопрос
answer|ответ
example|пример
rule|правило
idea|идея
thought|мысль
knowledge|знание
skill|навык
practice|практика
mistake|ошибка
progress|прогресс
goal|цель
result|результат
problem|проблема
solution|решение
reason|причина
choice|выбор
chance|шанс
change|изменение
future|будущее
past|прошлое
present|настоящее
work|работа
job|должность
team|команда
project|проект
plan|план
task|задача
meeting|встреча
office|офис
company|компания
customer|клиент
service|услуга
money|деньги
price|цена
market|рынок
shop|магазин
order|заказ
message|сообщение
email|электронное письмо
website|сайт
application|приложение
data|данные
file|файл
folder|папка
code|код
program|программа
system|система
network|сеть
search|поиск
information|информация
number|число
figure|цифра
pattern|закономерность
method|метод
research|исследование
science|наука
history|история
art|искусство
music|музыка
film|фильм
game|игра
sport|спорт
health|здоровье
body|тело
head|голова
hand|рука
eye|глаз
ear|ухо
heart|сердце
mind|разум
feeling|чувство
hope|надежда
dream|мечта
love|любовь
trust|доверие
help|помощь
support|поддержка
care|забота
kindness|доброта
curiosity|любопытство
journey|путешествие
adventure|приключение
experience|опыт
opportunity|возможность
challenge|вызов
success|успех
failure|неудача
effort|усилие
energy|энергия
attention|внимание
memory|память
habit|привычка
focus|сосредоточенность
balance|равновесие
freedom|свобода
community|сообщество
culture|культура
society|общество
nature|природа
environment|окружающая среда
education|образование
communication|общение
connection|связь
relationship|отношение
conversation|разговор
discussion|обсуждение
opinion|мнение
agreement|согласие
decision|решение
direction|направление
distance|расстояние
speed|скорость
size|размер
shape|форма
color|цвет
red|красный
blue|синий
green|зелёный
yellow|жёлтый
black|чёрный
white|белый
read|читать
write|писать
speak|говорить
listen|слушать
learn|учить
teach|преподавать
study|изучать
understand|понимать
remember|помнить
forget|забывать
think|думать
know|знать
believe|верить
imagine|представлять
create|создавать
build|строить
make|делать
do|выполнять
try|пробовать
start|начинать
finish|заканчивать
continue|продолжать
stop|останавливаться
wait|ждать
move|двигаться
walk|ходить
run|бегать
travel|путешествовать
arrive|прибывать
leave|уходить
return|возвращаться
find|находить
lose|терять
keep|сохранять
give|давать
take|брать
bring|приносить
send|отправлять
receive|получать
buy|покупать
sell|продавать
pay|платить
use|использовать
need|нуждаться
want|хотеть
like|нравиться
prefer|предпочитать
enjoy|получать удовольствие
choose|выбирать
decide|решать
ask|спрашивать
explain|объяснять
describe|описывать
show|показывать
share|делиться
meet|встречать
join|присоединяться
follow|следовать
lead|вести
grow|расти
improve|улучшать
develop|развивать
solve|решать
check|проверять
compare|сравнивать
measure|измерять
count|считать
analyze|анализировать
discover|открывать
explore|исследовать
notice|замечать
feel|чувствовать
hear|слышать
see|видеть
watch|смотреть
look|глядеть
touch|касаться
smile|улыбаться
laugh|смеяться
sleep|спать
wake|просыпаться
eat|есть
drink|пить
cook|готовить
clean|убирать
rest|отдыхать
play|играть
win|побеждать
change|менять
become|становиться
seem|казаться
remain|оставаться`;
const entries = new Map();
for (const line of RAW.split('\n')) {
  const [source, translation] = line.split('|');
  const old = entries.get(source);
  if (old) old.translation += `; ${translation}`;
  else entries.set(source, { id:`core:${entries.size}`, source, translation });
}
export const WORDS = [...entries.values()];
